# Generated by Django 4.2.1 on 2023-07-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='likes',
            new_name='icon_likes',
        ),
    ]
