# Generated by Django 4.2.1 on 2023-07-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='author',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='category',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='views',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
